import 'dart:convert';

Category categoryFromJson(String str) => Category.fromJson(json.decode(str));

String categoryToJson(Category data) => json.encode(data.toJson());

// To parse this JSON data, do
//
//     final category = categoryFromJson(jsonString);
// Generated by https://quicktype.io
class Category {
  final String name;
  final String description;
  final String color;
  final String icon;

  Category({
    required this.name,
    required this.description,
    required this.color,
    required this.icon,
  });

  factory Category.fromJson(Map<String, dynamic> json) => Category(
    name: json["name"],
    description: json["description"],
    color: json["color"],
    icon: json["icon"],
  );

  Map<String, dynamic> toJson() => {
    "name": name,
    "description": description,
    "color": color,
    "icon": icon,
  };
}
