import 'dart:convert';

Task taskFromJson(String str) => Task.fromJson(json.decode(str));

String taskToJson(Task data) => json.encode(data.toJson());

// To parse this JSON data, do
//
//     final Task = TaskFromJson(jsonString);
// Generated by https://quicktype.io
class Task {
  final String title;
  final String description;
  final DateTime deadline;
  final String priority;
  final bool involvesPatient;
  final String category;

  Task({
    required this.title,
    required this.description,
    required this.deadline,
    required this.priority,
    required this.involvesPatient,
    required this.category,
  });

  factory Task.fromJson(Map<String, dynamic> json) => Task(
    title: json["title"],
    description: json["description"],
    deadline: DateTime.parse(json["deadline"]),
    priority: json["priority"],
    involvesPatient: json["involves_patient"],
    category: json["category"],
  );

  Map<String, dynamic> toJson() => {
    "title": title,
    "description": description,
    "deadline": deadline.toIso8601String(),
    "priority": priority,
    "involves_patient": involvesPatient,
    "category": category,
  };
}
